#version: "13.3" 
version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
    # - POSTGRES_DB=d8bi10v2itva2d
    # - POSTGRES_USER=yzgljsysyahrwi
    # - POSTGRES_PASSWORD=24690a2be6569b81e78f2aff8725d0afc551dfc1ef66812be259afe197e56e9f


    - POSTGRES_DB=kittyitems
    - POSTGRES_USER=kittyuser
    - POSTGRES_PASSWORD=kittypassword